### ISSUE TITLE
Is it possible to publish your tool into a scoop bucket?

### ISSUE THREAD

**Issue by breakersun** [fasteddy516/SimplySerial#22]
Since scoop is getting more and more popular on windows platform, I think we can leverage it so make it easier for people to install your excelent tool.

Please consider [this](https://scoop-docs.vercel.app/docs/concepts/Buckets.html#creating-your-own-bucket)
Please let me know if I can help.

**Comment by YDX-2147483647** [comment]
I've worked out one.

```json
{
    "$schema": "https://raw.githubusercontent.com/lukesampson/scoop/master/schema.json",
    "version": "0.7.0",
    "description": "A serial terminal that runs as a Windows console application.",
    "homepage": "https://github.com/fasteddy516/SimplySerial",
    "license": "MIT",
    "url": "https://github.com/fasteddy516/SimplySerial/releases/download/v0.7.0/SimplySerial_0.7.0_standalone.zip",
    "hash": "a8a17cf3c0fdc0094713e8dc1db8bac66a04c40495ba5c8e4d45f67ced666eb8",
    "bin": "ss.exe",
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/fasteddy516/SimplySerial/releases/download/v$version/SimplySerial_$version_standalone.zip"
    }
}
```

Save it as `simply-serial.json` and try `scoop install ./simply-serial.json`.

_Remark_: Sorry I don't have time to meet all requirements for `extras` bucket now. Maybe later.

---

[The link you mention didn't update for 3 years.](https://github.com/kidonng/scoop-docs) We should read [community wiki](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests) and [`CONTRIBUTING.md`](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md) instead.

**Comment by YDX-2147483647** [comment]
Could you please reopen this issue?

[The PR to Extras bucket](https://github.com/ScoopInstaller/Extras/pull/10763) was made, but not merged yet. Therefore this is NOT completed.

@breakersun

(If you feel noisy, you can unsubscribe, or just tell me to open a new issue.)

**Comment by YDX-2147483647** [comment]
Update: https://github.com/ScoopInstaller/Extras/pull/10763 is merged! 🎉 Checkout [the extras bucket](https://scoop.sh/#/apps?q=simplyserial&s=0&d=1&o=true).

```powershell
> scoop install simplyserial
```

Note that the app is renamed to `simplyserial` (no dash between words).

**Comment by fasteddy516** [comment]
This is an awesome installation option, thanks for your efforts getting it set up - and for introducing me to scoop!

**Comment by jevogel** [comment]
Hi @fasteddy516, would you consider adding your package to the Windows Package Manager (aka `winget`) as well?

[Submit your manifest to the repository (learn.microsoft.com)](https://learn.microsoft.com/en-us/windows/package-manager/package/repository)
