### ISSUE TITLE
Command line option to log all serial data to a file

### ISSUE THREAD

**Issue by unwiredben** [fasteddy516/SimplySerial#9]
I'd like to use this to monitor several embedded devices connected over COM ports to my Windows box.  This works great for getting the data into a terminal window, but I'd like a way to specify a file where all the received bytes can also be written for later analysis.  I'd suggest

- -log:\<path to logging file\>
- -logappend:\<path to logging file\>

with -log replacing the file and -logappend appending to an existing file

**Comment by fasteddy516** [comment]
I assume for your use case you're ok with the terminal window/process remaining open for the duration of the session you want to log.  (SimplySerial is a C# console application with no provisions for running in the background.)  If a `-log` option was implemented such that the application behaves exactly as it does now, but writes everything that it prints on the screen to a file as well, would that suffice?

**Comment by unwiredben** [comment]
Yep, that's exactly what I want -- basically, I'm debugging devices that log a lot of data, so want to be able to go back and check the logs if something goes wrong without worrying about the terminal scrollback.

**Comment by fasteddy516** [comment]
I've started working on this, and hope to have it done in the next day or two - it depends on how quickly I can get up to speed on C# file operations.  The command line arguments will be:

`-log:<path to log file>`
`-logmode:<append | overwrite>`

If no `logmode` is specified, it will default to `overwrite` mode.

**Comment by Hamanstone** [comment]
I am so glad to hear that this project still activity.
well anyway, you guys did a great job. I love this project so much. 
Thank you guys.

**Comment by fasteddy516** [comment]
I've posted [SimplySerial 0.5.0-beta](https://github.com/fasteddy516/SimplySerial/releases/tag/v0.5.0-beta) in the [releases section](https://github.com/fasteddy516/SimplySerial/releases) with the requested logging functionality.  You can give it a try and let me know if you run into any issues.  There were a fair amount of under-the-hood changes required throughout the code, and my experience with C#/.NET file operations is minimal, so I've marked it as a pre-release for now, and will issue a full release after there has been sufficient real-world testing.

**Comment by unwiredben** [comment]
Initial test looks good, but I think you should add some sort of timeout to the write thread -- for example, if there's no serial data in 500ms, flush the buffer.   I often see bursty serial traffic, and I was noticing that I could easily have a few lines left off the end when I did a "type device.log" even after a few seconds with the default 4096 bytes.

**Comment by unwiredben** [comment]
I used the system installer.  I think the "ml" at the end of that is "machine learning", which means it looked for a pattern it didn't like.  On my own system, I just added it to the whitelist and haven't had a problem.

**Comment by fasteddy516** [comment]
I've done a fair bit of testing with the new logging functionality over the last few days, and am happy with how it is working.  I've published the release version of 0.5.0, which does fix one bug with regards to the automatic buffer flushing, so it is worth updating,

I'd still love to know what behaviour triggered Windows Defender, but I haven't been able to duplicate that on any of my machines or SimplySerial installations.  Regardless, I'm planning on a fairly extensive re-write (for a number of reasons) for version 0.6.0, and am also hoping to learn enough about Github Actions to set up an automated build process and remove my machine from the build process completely.

**Comment by unwiredben** [comment]
It's been working very well, thanks so much!
